# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: whole-mapel-pub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]*'
env:
  WHL_HOUSE: wheelhouse

permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: make sdists
      run: |
        mkdir -p $WHL_HOUSE
        python -m pip install build 
        python -m build --sdist --outdir $WHL_HOUSE ./mapel-all/
        python -m build --sdist --outdir $WHL_HOUSE ./mapel-core/
        python -m build --sdist --outdir $WHL_HOUSE ./mapel-elections/ 
        python -m build --sdist --outdir $WHL_HOUSE ./mapel-roommates/
        python -m build --sdist --outdir $WHL_HOUSE ./mapel-marriages/
        ls ./$WHL_HOUSE # Listing the contents of ./$WHL_HOUSE for a sanity check
        
    # Due to the fact that the manylinyux action (the following one)
    # runs everything as root, it is MANDATORY to first build sdists (the action above).
    # The issue is that for mapel-elections (the only package containing
    # a C++ extension), the manylinux action creates a directory mapel-elections/src/mapel_elections.egg-info
    # as root. However, the sdist action wants to use this package as no-root
    # which causes permission denied error!
    
    - name: Build manylinux Python wheels-elections
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310'
        build-requirements: 'pybind11'
        package-path: 'mapel-elections'
        system-packages: 'gcc gcc-c++'
        pip-wheel-args: '-w ../${{ env.WHL_HOUSE }} --no-deps'
    - name: Build pure-Python wheels
      run: |
        pip wheel ./mapel-all --no-deps -w $WHL_HOUSE
        pip wheel ./mapel-core --no-deps -w $WHL_HOUSE
        pip wheel ./mapel-roommates --no-deps -w $WHL_HOUSE
        pip wheel ./mapel-marriages --no-deps -w $WHL_HOUSE
        ls ./$WHL_HOUSE # Listing the contents of ./$WHL_HOUSE for a sanity check
        ###    - name: Publish distribution 📦 to PyPI
        ###      uses: pypa/gh-action-pypi-publish@release/v1
        ###      with:
        ###        password: ${{ secrets.PYPI_API_TOKEN }}
        ###        packages_dir: $WHL_HOUSE/
        ###        verbose: true
